/* autogenerated by Processing revision 1308 on 2025-10-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_basic_movement extends PApplet {

PImage ejemplo;
int imgx = 0;
int imgy = 0;

public void setup () {
    /* size commented out by preprocessor */;
    background(0xFF000000);
    ejemplo = loadImage("./src/ejemplo.jpg");
}

public void draw () {
    background(0xFF000000);
    image(ejemplo, imgx, imgy);
}

public void keyPressed () {
    if (keyCode == UP) {
        imgy -= 5; 
    } else if (keyCode == DOWN) {
        imgy += 5;
    } else if (keyCode == LEFT) {
        imgx -= 5;
    } else if (keyCode == RIGHT) {
        imgx += 5;
    }
}


  public void settings() { size(960, 540, P2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_basic_movement" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
