/* autogenerated by Processing revision 1308 on 2025-10-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_basic_circle_rbg extends PApplet {

public void setup () {
    /* size commented out by preprocessor */;
    background(0xFF000000);
    noStroke();
}
public void draw () {
    fill(0xFFFFFFFF);
    if (keyPressed) {
        if (key == 'r' || key == 'R') 
            fill(0xFFFF0000);
        if (key == 'g' || key == 'G') 
            fill(0xFF00FF00);
        if (key == 'b' || key == 'B') 
            fill(0xFF0000FF);
        if (key == 'p' || key == 'P') 
            fill(0xFFFF00FF);
        if (key == 'y' || key == 'Y') 
            fill(0xFFFFFF00);
        if (key == 'm' || key == 'M')
            fill(random(255), random(255), random(255));
        if (key == 'c' || key == 'C') 
            background(0xFF000000);
    }
    circle(mouseX, mouseY, random(1000, 10000));
}


  public void settings() { size(960, 540, P2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_basic_circle_rbg" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
