/* autogenerated by Processing revision 1308 on 2025-10-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_basic_whiteboard extends PApplet {

public void setup () {
    /* size commented out by preprocessor */;
    background(0);
}
public void draw () {
    stroke(255);
    if (mousePressed) {
        line(mouseX, mouseY, pmouseX, pmouseY);
    }
}


  public void settings() { size(960, 540, P2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_basic_whiteboard" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
